### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by MysteryBlokHed** [MysteryBlokHed/databind#1]
Add support for a TOML configuration file that lets you configure what/how Databind transpiles.

It should look something like this:

`databind.toml`

```toml
random_var_names = false
var_display_names = false
# Whether to auto-generate function JSON in minecraft/tags/functions
generate_func_json = true
# Functions not to generate JSON for
func_json_exclusions = [
    "main",
    "loop1"
]
```

Any values that aren't lists should also be passable as CLI arguments. An optional `--config`/`-c` argument should be added to specify the location of a config file. If the argument is not passed, Databind should look for a config file in the directory it's being run in. Otherwise, use default settings.
