### ISSUE TITLE
Change project to a library with a binary file

### ISSUE THREAD

**Issue by MysteryBlokHed** [MysteryBlokHed/databind#129]
Instead of Databind only being available as a CLI, changing it to a library with a binary available would make it possible for other developers to write their own frontends to Databind or to embed it in their own applications. I haven't tried it, but rust already seems to support it with something like the following added to the `Cargo.toml` file of a library:

```toml
[[bin]]
name = "databind"
path = "src/main.rs"
```
