### ISSUE TITLE
Implement incremental compilation

### ISSUE THREAD

**Issue by MysteryBlokHed** [MysteryBlokHed/databind#79]
Right now, Databind will recompile every file in a project when built, even though it's unlikely that every file in a project has changed. In large projects, this can be a significant problem. I'm not certain how other incremental compilers make sure to only recompile changed files, but doing something like creating a `.databind` folder in a project's root with the SHA256 hashes of files could work.

In an example implementation, the following tree:

```txt
src
└──data
    └──namespace
        └──functions
               main.databind
```

would result in the following `.databind` folder:

```txt
.databind
└──src
    └──data
        └──namespace
            └──functions
                   main.databind.info
```

Before file's signatures are checked, the file modification date should be checked. There's no reason to check the hash of a file if it hasn't been modified. This could be stored in the same file as the hash, resulting in the following contents for `main.databind.info`:

```txt
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 1626831659
```

Where `e3b0c442...` is the file's hash, and `1626831659` is the Unix time of the file.

**Comment by MysteryBlokHed** [comment]
It might be better to have a single file in the `.databind` folder that contains all of the hashes/modification dates for the files. The structure for this would look much simpler:

```
.databind
│   modified
```

Where `modified` would contain something like the following for a single `main.databind` file:

```
src/data/namespace/functions/main.databind e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 1626831659
```

**Comment by MysteryBlokHed** [comment]
With the addition of global macros in #78, it would also be necessary to store information on files with calls to global macros. The best way to do this would probably be to save which files depend on which other files during compilation.

For example, if there's a file `@macros.databind` with a definition for a macro called `hello_world`, and there's another file `main.databind` that calls that macro, then `main.databind` would depend on `@macros.databind`. This means that even if `main.databind` is unchanged, if `@macros.databind` changes, `main.databind` needs to be recompiled.

**Comment by MysteryBlokHed** [comment]
A better solution than trying to create a new parser for something like this would be to just use TOML again. A file in the path `.databind/files.toml` in the root of the project could contain something like the following:

```toml
# This file is used by Databind and contains information about files
# and their modification to make compilation faster.
# It should not be modified.
[[file]]
path = "src/data/example/functions/!macros.databind"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
modified = 2021-08-23T15:32:53Z
depends_on = []

[[file]]
path = "src/data/example/functions/main.databind"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
modified = 2021-08-23T15:35:47Z
depends_on = ["src/data/example/functions/!macros.databind"]

```
